@startuml
'https://plantuml.com/activity-diagram-beta
title Memo API 설계 Put Memo

start
:/api/v1/memo/{date} \n PUT;
if (로그인 여부) then (비정상)
 -> 401 error;
    end
endif
#green: 트랜젝션 시작;
: 가비지 메모(식별자 없고 content가 Empty)를 제외;
if (메모 추가없이 전체삭제인가?)
    ->맞음;
    if(해당일자의 메모가 이미 없는가?) then (맞음)
    else
    -> 아님;
    :해당일정 메모를 삭제해서 비움;
    endif
else
    -> 아님;
    : 메모의 추가/ 수정/ 삭제 구분;
    : 메모 삭제;
    if (수정요청메모의 DB일관성 검증) then
        -> 400 error;
        end
    endif
    : 메모 수정;
    : 메모 추가;
endif
#green: 트랜젝션 종료;
-> 200 OK;
stop
@enduml
